# src/main/resources/application-prod.properties

# Configuración para el entorno de producción (usar variables de entorno)
# spring.datasource.url=${PROD_DB_URL}
# spring.datasource.username=${PROD_DB_USER}
# spring.datasource.password=${PROD_DB_PASSWORD}
# spring.datasource.driver-class-name=org.postgresql.Driver