# Configuración de la base de datos para NeonDB
spring.datasource.url=jdbc:postgresql://ep-bitter-snow-acx25u90-pooler.sa-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_vOpd3tExINe4
spring.datasource.driver-class-name=org.postgresql.Driver